// @ts-check
/**
 * What a new repository for a game project should ignore and how it should
 * treat the files it keeps.
 *
 * Pure string building, so `npm run test:git` can assert the actual content
 * rather than "a file was written".
 *
 * ## The two decisions encoded here
 *
 * 1. **`.meta` sidecars are committed.** They carry import settings — colour
 *    space, filtering, flipY, sprite pivots — that are authored, not derived.
 *    A teammate who clones a project without them gets textures that look
 *    subtly wrong and nothing to point at. `engine-types/` is the opposite:
 *    it is a vendored copy of `@types/three` the editor rewrites on open, so
 *    committing it means thousands of generated files in every diff.
 * 2. **Binary assets go to Git LFS from the first commit.** This is the one
 *    thing about a game repository that cannot be fixed later: a 300 MB `.glb`
 *    committed once is in the history forever, and every future clone pays for
 *    it. Migrating afterwards means rewriting history, which breaks every
 *    checkout anyone else has. Deciding at `init` is nearly free; deciding at
 *    commit 400 is a project-wide event.
 */

/**
 * Extensions tracked by LFS.
 *
 * Deliberately excludes formats that only *look* binary: `.gltf`, `.obj`,
 * `.mtl` and this engine's `.scene`/`.mat`/`.prefab`/`.atlas` are text, and
 * putting text in LFS costs the thing text is good for — a readable diff.
 */
export const LFS_PATTERNS = [
  // Models
  "*.glb",
  "*.fbx",
  "*.blend",
  "*.geom",
  "*.bin",
  // Images
  "*.png",
  "*.jpg",
  "*.jpeg",
  "*.gif",
  "*.webp",
  "*.tga",
  "*.psd",
  "*.tif",
  "*.tiff",
  "*.exr",
  "*.hdr",
  "*.ktx2",
  "*.basis",
  "*.dds",
  // Audio
  "*.wav",
  "*.mp3",
  "*.ogg",
  "*.opus",
  "*.flac",
  "*.m4a",
  // Video and fonts
  "*.mp4",
  "*.webm",
  "*.ttf",
  "*.otf",
  "*.woff",
  "*.woff2",
  // Archives
  "*.zip",
];

/**
 * The default ignore list.
 *
 * @param {{ outDir?: string }} [options] `outDir` is the project's configured
 *   build folder, which is not always "Build" — ignoring the wrong one means a
 *   whole exported game shows up as 900 files to commit.
 */
export function defaultGitignore({ outDir = "Build" } = {}) {
  const build = String(outDir || "Build").replaceAll("\\", "/").replace(/^\.\//, "").replace(/\/$/, "");
  return `# Written by the editor when this project's repository was created.
# Everything not listed here — scenes, prefabs, materials, scripts, assets and
# their .meta sidecars — is part of the project and belongs in version control.

# Build output. Regenerated by Build; committing it doubles the repository.
/${build}/
/dist/

# Type definitions the editor vendors into the project on open. Generated from
# the engine version, thousands of files, and rewritten whenever it changes.
/engine-types/

# Dependencies, if project scripts ever grow any.
node_modules/

# Local editor state that is about this machine, not about the game.
*.log
.DS_Store
Thumbs.db
desktop.ini
`;
}

/**
 * The default attributes file.
 *
 * @param {{ lfs?: boolean }} [options] With `lfs: false` the same file is
 *   written minus the filter lines — line-ending normalisation is worth having
 *   even where git-lfs is not installed, and adding filters for a filter driver
 *   that does not exist makes every checkout print an error.
 */
export function defaultGitattributes({ lfs = true } = {}) {
  const header = `# Written by the editor when this project's repository was created.

# The editor writes its assets as JSON. Normalising line endings keeps a scene
# saved on Windows from showing up as a whole-file change on macOS.
* text=auto eol=lf

# Formats that are text despite the extension, stated so nothing guesses wrong.
*.scene text
*.mat text
*.prefab text
*.anim text
*.timeline text
*.post text
*.atlas text
*.meta text
*.gltf text
`;
  if (!lfs) return header;
  return `${header}
# Binary assets live in Git LFS: they never merge usefully, they dominate clone
# size, and moving them here later would mean rewriting history.
${LFS_PATTERNS.map((pattern) => `${pattern} filter=lfs diff=lfs merge=lfs -text`).join("\n")}
`;
}

/**
 * Adds any missing lines to a file that already exists, leaving the rest alone.
 *
 * Used instead of overwriting because a project may already be a repository
 * with an ignore list its author wrote — replacing that would be the editor
 * deleting someone's configuration to install its own opinion. Returns null
 * when there is nothing to add, so the caller can skip the write entirely.
 *
 * @param {string} existing
 * @param {string} wanted
 * @param {string} note Comment introducing the appended block.
 */
export function mergeLines(existing, wanted, note = "# Added by the editor.") {
  const current = String(existing ?? "");
  const have = new Set(
    current
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean),
  );
  const missing = wanted
    .split("\n")
    .map((line) => line.replace(/\r$/, ""))
    .filter((line) => {
      const trimmed = line.trim();
      // Comments and blanks are formatting, not rules — re-adding them on
      // every merge would grow the file without changing its meaning.
      return trimmed && !trimmed.startsWith("#") && !have.has(trimmed);
    });
  if (!missing.length) return null;
  const separator = current.length && !current.endsWith("\n") ? "\n" : "";
  return `${current}${separator}\n${note}\n${missing.join("\n")}\n`;
}

/**
 * A commit message for the first commit, naming the project so a repository
 * page says what it holds.
 * @param {string} projectName
 */
export function initialCommitMessage(projectName) {
  const name = String(projectName ?? "").trim();
  return name ? `Initial commit: ${name}` : "Initial commit";
}
